spring:
  application:
    name: config_service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/AbdulatipA/wallet_config.git
          default-label: main
          search-paths: .
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh,loggers,env
  endpoint:
    health:
      show-details: always

server:
  port: 8888